### ISSUE TITLE
Configure clustering

### ISSUE THREAD

**Issue by retr0h** [Mayeu/ansible-playbook-rabbitmq#12]
Configure role to setup rabbitmq clustering.  Will work on implementing this once #9 is merged.

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨
