### ISSUE TITLE
Adding a way to load a custom RabbitMQ conf

### ISSUE THREAD

**Issue by Mayeu** [Mayeu/ansible-playbook-rabbitmq#2]
Generating complete config file seems almost impossible with Ansible. (Or really, really cucumbersome). Adding a way to check if there is a config file available (eithers in `files` or `templates`) is certainly a good idea.

**Comment by BarthV** [comment]
:question: 
Do you plan to make this live ?

Maybe we can start by using a boolean to enable or disable default configuration and let wrapper do the whole configuration job ?

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨
