### ISSUE TITLE
Add how to activate plugins in the documentation

### ISSUE THREAD

**Issue by mnothic** [Mayeu/ansible-playbook-rabbitmq#42]
I don't see how activate plugins you can put an example in the documentation?

**Comment by Mayeu** [comment]
I'll add something about that in the documentation.
In the mean time, what you should do is to fill the list of plugins with the following variable:
```yaml
rabbitmq_plugins:
  - plugins1
  - plugins2
```

See the [plugins.yml file in the playbook](https://github.com/Mayeu/ansible-playbook-rabbitmq/blob/master/tasks/plugins.yml). Note that all non-listed plugin will be disabled.

**Comment by jamescarr** [comment]
This is actually in the readme.
