### ISSUE TITLE
Error when using it with latest Ansible

### ISSUE THREAD

**Issue by palvarez89** [Mayeu/ansible-playbook-rabbitmq#57]
The error I'm having is:

    TASK [Mayeu.RabbitMQ : add the official rabbitmq repository] *******************
    fatal: [storyboard]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/home/pedro/Documents/repos/files/rabbitmq.list"}

**Comment by Mayeu** [comment]
Hello,
This [commit](39422b14) should fix this. I'm going to publish a tag later on, in the mean time you can try master.
Feel free to reopen if you still experiment this issue :)

**Comment by jbradberry** [comment]
@Mayeu can you please cut a new release that includes this?
