### ISSUE TITLE
Rabbitmq cannot be authenticated!

### ISSUE THREAD

**Issue by ch0k0bn** [Mayeu/ansible-playbook-rabbitmq#60]
Rabbitmq has changed its release signing key on May 25th. New one is there:
http://www.rabbitmq.com/rabbitmq-release-signing-key.asc

(src: https://www.rabbitmq.com/news.html#2016-05-25T18:00:00+03:00)

**Comment by Mayeu** [comment]
This has been fixed in master (see commit 67dea74), I'll publish a tag with the fix later on.
