### ISSUE TITLE
Potential Issue with Ansible 2.2.0.0

### ISSUE THREAD

**Issue by codereviewvideos** [Mayeu/ansible-playbook-rabbitmq#63]
Having not had to use Ansible for a couple of weeks, I keep hitting on these issues today. Having recently updated to Ansible 2.2.0.0, I now get a lot of these:

``` 
TASK [Mayeu.RabbitMQ : add rabbitmq vhost] *************************************
task path: /home/chris/Development/ansible-submodule/roles/Mayeu.RabbitMQ/tasks/vhost.yml:5
fatal: [tribecount.dev]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'name'\n\nThe error appears to have been in '/home/chris/Development/ansible-submodule/roles/Mayeu.RabbitMQ/tasks/vhost.yml': line 5, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: add rabbitmq vhost\n  ^ here\n"
}
```

The fix is easy enough: 

``` language-yaml
---
- name: ensure rabbitmq is runned
  service: name=rabbitmq-server state=started

- name: add rabbitmq vhost
  rabbitmq_vhost: >
    name={{ item.name }}
    node={{ item.node | default('rabbit') }}
    tracing={{ item.tracing | default('no') }}
    state=present
  with_items: rabbitmq_vhost_definitions
```

needs to be:

``` language-yaml
---
- name: ensure rabbitmq is runned
  service: name=rabbitmq-server state=started

- name: add rabbitmq vhost
  rabbitmq_vhost: >
    name={{ item.name }}
    node={{ item.node | default('rabbit') }}
    tracing={{ item.tracing | default('no') }}
    state=present
  with_items: "{{ rabbitmq_vhost_definitions }}"
```

same for `  with_items: "{{ rabbitmq_users_definitions }}"`

not sure if it's just me somehow yet :/ frustrating all the same, hope this helps someone along the way

lmk if anyone else sees the same, happy to put a PR together

**Comment by s01ipsist** [comment]
👍 
Implemented by https://github.com/Mayeu/ansible-playbook-rabbitmq/pull/62/files

**Comment by Mayeu** [comment]
Thank you for your contribution.

Sadly, and has you may have guessed, I don't use this project anymore, nor do I have the time to continue to maintain it. I may at some point start to use it again, but that is not on my priority right now.

Feel free to fork and improve, I can even link potential fork in the README.

Wishing you the best, and a gajillion more contribution in your lifetime 🙏✨
